config/routes.rb
Rails.application.routes.draw do
  resources :share_model_buckets
  resources :share_models
  resources :salaries
  resources :spendings
  get 'welcome/index'

  resources :associates
  resources :incomes

  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/associate.rb
require './app/services/associate'

class Associate < ApplicationRecord
  has_many :incomes
  has_many :spendings
  has_many :salaries

  class << self
    def from_omniauth(auth_hash)
      first_associate = all.size == 0
      find_or_create_by(oauth_uid: auth_hash['uid'], oauth_provider: auth_hash['provider']) do |associate|
        # The first one to connect gets access
        # The following need to get the access from someone else
        if first_associate then
          associate.access = true
        end
        associate.display_name = auth_hash['info']['name']
        associate.email = auth_hash['info']['email']
        associate.save!
      end
    end
  end

  def data_by_month
    AssociateService.data_by_month(self)
  end

  def summary
    AssociateSummary.new(self.incomes, self.salaries, self.spendings)
  end
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
    before_action :set_associate, only: [:show, :edit, :update, :destroy]

    def show
        @associate = Associate.find(params[:id])
        @summary = @associate.summary
    end

    def index
        @associate = Associate.all
    end


    def new
        @associate = Associate.new
    end

    def create
        @associate = Associate.new(associate_params)

        @associate.save
        redirect_to @associate
    end

    def edit
    end

    def update
        if @associate.update(associate_params)
            redirect_to @associate, notice: 'Associé·e mis à jour.'
        else
            render :edit
        end
    end

    private

    def set_associate
        @associate = Associate.find(params[:id])
    end

    def associate_params
        params.require(:associate).permit(:display_name, :email, :access)
    end
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/views/associates/_form.html.erb
<%= form_with(model: associate, local: true) do |form| %>
  <% if associate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(associate.errors.count, "error") %> prohibited this associate from being saved:</h2>

      <ul>
      <% associate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
        <%= form.label :display_name, "Nom d’usage" %><br>
        <%= form.text_field :display_name %>
    </div>

    <div class="field">
        <%= form.label :email, "Adresse courriel" %><br>
        <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :access, "Accès au site" %><br>
        <%= form.check_box :access %>
    </div>
    
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/associates/edit.html.erb
<h1>Édition de l’associé·e</h1>

<%= render 'form', associate: @associate %>

<%= link_to 'Voir', @associate %> |
<%= link_to 'Retour', associate_path %>

app/views/associates/index.html.erb
<h1>Liste des associés</h1>

<ul>
  <% @associate.each do |associate| %>
    <li>
      <%= link_to associate.display_name, associate_path(associate) %>
        <%= associate.email %>
        <% if associate.access %>(accès autorisé)<% end %>
        | <%= link_to "Modifier", edit_associate_path(associate) %>
      </li>
  <% end %>
</ul>

app/views/associates/show.html.erb
<% if flash.notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<% if flash.alert %>
  <p id="alert"><%= flash.alert %></p>
<% end %>

<div class="container">
  <div class="main-panel">
    <p>
      Bonjour <strong><%= @associate.display_name %></strong>
    </p>
    <%= form_for @associate.spendings.new, remote: true do |f| %>
    <%= f.hidden_field :associate_id, value: @associate.id %>
    <div class="field">
      <div class="input-group">
        <div class="input-group__inline">
          <%= f.label :amount, "Montant de la dépense" %>
          <%= f.number_field :amount, min: 0, :step => 0.01 %>
        </div>
        <div class="input-group__inline">
          <%= f.label :label, "Libellé de la dépense" %>
          <%= f.text_field :label %>
        </div>
      </div>
      <div class="input-group">
        <%= select_date(Date.today, order: [:month, :year], prefix: :spending) %>
      </div>
      <%= f.submit 'Ajouter la dépense'%>
    </div>
    <% end %>
    <hr />
    <%= form_for @associate.incomes.new, remote: true do |f| %>
    <%= f.hidden_field :associate_id, value: @associate.id %>
    <div class="field">
      <div class="input-group">
        <div class="input-group__inline">
          <%= f.label :amount, "Revenu (Hors TVA)" %>
          <%= f.number_field :amount, min: 0, :step => 0.01 %>
        </div>
        <div class="input-group__inline">
          <%= f.label :label, "Libellé du revenu" %>
          <%= f.text_field :label %>
        </div>
      </div>
      <div class="input-group">
        <%= select_date(Date.today, order: [:month, :year], prefix: :income) %>
      </div>
      <div class="input-group">
        <%= f.label :label, "Modèle de répartition" %>
        <%= f.collection_select :share_model, ShareModel.all, :id, :label %>
      </div>
      <%= f.submit 'Ajouter le revenu' %>
    </div>
    <% end %>
    <hr />
    <%= form_for @associate.salaries.new, remote: true do |f| %>
      <%= f.hidden_field :associate_id, value: @associate.id %>
      <div class="field">
        <div class="input-group">
          <%= f.label :net_pay, "Salaire net" %> <%= f.number_field :net_pay, min: 0, :step => 0.01 %>
        </div>
        <div class="input-group">
          <div class="input-group__inline">
            <%= f.label :employee_contribution, "Cotisation salariale" %> <%= f.number_field :employee_contribution, min: 0, :step => 0.01 %>
          </div>
          <div class="input-group input-group__inline">
            <%= f.label :employer_contribution, "Cotisation patronale" %> <%= f.number_field :employer_contribution, min: 0, :step => 0.01 %>
          </div>
        </div>
        <div class="input-group">
          <%= f.label :saving_plan_contribution, "Versement volontaire PEE/PERCO" %> <%= f.number_field :saving_plan_contribution, min: 0, :step => 0.01 %>
        </div>
        <div class="input-group">
          <%= select_date(Date.today, order: [:month, :year], prefix: :salary) %>
        </div>
        <%= f.submit 'Ajouter le salaire' %>
      </div>
    <% end %>

    <% @associate.data_by_month.each do |month, data| %>
      <h2><%= I18n.l(Date.new(month[0], month[1]), format: '%B %Y') %></h2>
      <% if data[:spending] %>
        <h3> Dépenses </h3>
        <ul>
          <% data[:spending].each do |spending| %>
            <li>
              <%= spending.amount.displayed_euros %> (<%= spending.label %>)
              <%= link_to 'Supprimer', spending, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: "delete" %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <% if data[:income] %>
        <h3> Revenus </h3>
        <ul>
          <% data[:income].each do |income| %>
            <li>
              <%= income.amount.displayed_euros %> (<%= income.label %>, répartition : <%= income.share_model.label %>)
              <%= link_to 'Supprimer', income, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: "delete" %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <% if data[:salary] %>
        <h3> Salaires </h3>
        <ul>
          <% data[:salary].each do |salary| %>
            <li>
              Net : <%= salary.net_pay.displayed_euros %>
            </li>
              <% if salary.saving_plan_contribution > 0 %>
            <li>
              Abondement PEE/PERCO : <%= salary.employer_matching.displayed_euros %>
            </li>
              <% end %>
            <li>
              Cotisations salariales : <%= salary.employee_contribution.displayed_euros %>
            </li>
            <li>
              Cotisations patronales : <%= salary.employer_contribution.displayed_euros %>
            </li>
            <%= link_to 'Supprimer', salary, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: "delete" %>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>

  <aside class="side-panel">
    <ul>
      <li><strong>Bilan :</strong> <%= @summary.net_balance.displayed_euros %></li>
      <li><strong>Prime proposée :</strong> <%= @summary.suggested_bonus.displayed_euros %></li>
    </ul>
  </aside>
</div>
<div class="button-group">
  <%= link_to 'Modifier le compte', edit_associate_path(@associate), class: "button" %>
  <%= link_to 'Retour à la liste des associés', associates_path, class: "button" %>
</div>